apiVersion: "app.redislabs.com/v1alpha1"
kind: "RedisEnterpriseCluster"
metadata:
  name: "redis-enterprise"
spec:
  nodes: 3
  uiServiceType: LoadBalancer
  username: "thomas.osaland@bouvet.no"
  redisEnterpriseNodeResources:
    limits:
      cpu: "2000m"
      memory: 2Gi
    requests:
      cpu: "2000m"
      memory: 2Gi
